name: CI/CD Node.js Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  deploy:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # Important pour pousser sur gh-pages

      - name: Générer le fichier index.html
        run: |
            cat > index.html << 'EOF'
            <!DOCTYPE html>
            <html lang="fr">
            <head>
            <meta charset="UTF-8">
            <title>Générateur de citations</title>
            </head>
            <body>
            <h1 id="citation"></h1>
            <p>Voici la citation</p>
            <script type="module">
            import citationAleatoire from "./src/app.js";
            document.getElementById("citation").innerText = citationAleatoire();
            </script>
            </body>
            </html>
            EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./           # Ici le dossier contenant index.html
